import 'package:freezed_annotation/freezed_annotation.dart';
// import 'package:flutter/foundation.dart';
//
// required: associates our `main.dart` with the code generated by Freezed
part 'category.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'category.g.dart';

@freezed
class RecipeCategory with _$RecipeCategory {
  const factory RecipeCategory({
    required String title,
    required bool isSelected,
  }) = _RecipeCategoryCategory;

  factory RecipeCategory.fromJson(Map<String, Object?> json)
  => _$RecipeCategoryFromJson(json);
}